---
title: "Reading Data From the Web"
output: github_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(rvest)
library(httr)
```


This document will show how to Read Data from the Web.

## Importing Data From HTML

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html |>
  html_table()
```

```{r}
table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() |> 
  slice(-1)
```


### Learning Assessment

Create a data frame that contains the cost of living table for New York.

```{r}
nyc_cost = 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") |> 
  html_table(header = TRUE) |> 
  first()
```


## CSS Selectors

This is how to use CSS Selectors to pick certain elements in an html.

```{r}
swm_url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(swm_url)
```

```{r}
swm_title_vec =
  swm_html |> 
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |> 
  html_text()

swm_runtime_vec =
  swm_html |> 
  html_elements(".dli-title-metadata-item:nth-child(2)") |> 
  html_text()

swm_score_vec =
  swm_html |> 
  html_elements(".metacritic-score-box") |> 
  html_text()

swm_df = 
  tibble (
    title = swm_title_vec,
    score = swm_score_vec,
    runtime = swm_runtime_vec)
```


Let's import some books.

```{r}
url = "http://books.toscrape.com"

books_html = read_html(url)

books_titles = 
  books_html |>
  html_elements("h3") |>
  html_text2()

books_stars = 
  books_html |>
  html_elements(".star-rating") |>
  html_attr("class")

books_price = 
  books_html |>
  html_elements(".price_color") |>
  html_text()

books = tibble(
  title = books_titles,
  stars = books_stars,
  price = books_price
)
```


## Using an API

Get water data.

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content()
```

Get BRFSS data

```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content()
```

Pokemon API

```{r}
pokemon = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |> 
  content()
```

